In [1]:
import numpy as np

In [2]:
my_array = np.array([1, 2, 3, 4, 5])
type(my_array)

numpy.ndarray

In [3]:
x = np.arange(1, 5)  # from 1 inclusive to 5 exclusive

In [4]:
big_matrix = np.random.randn(10, 5)
big_matrix

array([[-0.80819159, -0.46523026,  0.2777297 ,  0.40222083,  2.32485373],
       [ 1.07053991,  0.79951567, -0.20742304,  0.22050429,  0.89980654],
       [ 0.84797625, -0.31907134, -0.08546302, -1.19978321, -0.47535561],
       [-2.08924122,  0.42834465,  1.03227027,  2.17277946,  0.05527258],
       [ 1.24033842, -0.8335218 , -0.30016706, -1.76986532,  0.4756984 ],
       [-0.58747702, -0.27471063, -0.75634332, -0.79082825,  0.06489768],
       [-1.88889399,  1.58673478,  1.29962025, -1.45687658, -0.69542754],
       [ 0.20638581,  1.29472767,  0.22021086,  0.67148855,  0.25347501],
       [-0.36811001, -1.26225309, -0.65832699, -0.91499472, -0.78627285],
       [-0.19893714, -0.33348113, -0.45291359, -1.24342176,  0.68395822]])

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[3]

3

In [7]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x[2:5]

array([2, 3, 4])

In [16]:
x = np.random.randint(10, size=(4, 6))
x

array([[5, 9, 4, 9, 9, 6],
       [5, 6, 9, 4, 3, 1],
       [6, 8, 1, 7, 2, 4],
       [4, 2, 2, 2, 0, 4]])